/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Form;

import DB.DBAccess;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.activation.DataHandler;
import javax.activation.DataSource;

/**
 *
 * @author DELL
 */
public class frmOTP extends javax.swing.JFrame {
    private int userId;

    /** Creates new form frmOTP */
    public frmOTP() {
        this.userId = userId;
    initComponents();
    }
    public frmOTP(int userId) {
        this.userId = userId;
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtotp = new javax.swing.JTextField();
        btnxacnhan = new javax.swing.JButton();
        btnguilai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnxacnhan.setText("xac nhan");
        btnxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxacnhanActionPerformed(evt);
            }
        });

        btnguilai.setText("gui lai");
        btnguilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguilaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnxacnhan)
                        .addGap(158, 158, 158)
                        .addComponent(btnguilai))
                    .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxacnhan)
                    .addComponent(btnguilai))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxacnhanActionPerformed
        String otp = txtotp.getText();

    if (otp.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã OTP!");
        return;
    }

    try {
        DBAccess db = new DBAccess();
        String query = "SELECT * FROM OTPs WHERE UserID = " + userId + " AND OTPCode = '" + otp
                + "' AND ExpiryTime > CURRENT_TIMESTAMP AND IsUsed = FALSE";
        ResultSet rs = db.Query(query);

        if (rs.next()) {
            // Cập nhật trạng thái xác minh
            String updateUserQuery = "UPDATE Users SET IsVerified = TRUE WHERE UserID = " + userId;
            db.Update(updateUserQuery);

            // Đánh dấu OTP đã sử dụng
            String updateOtpQuery = "UPDATE OTPs SET IsUsed = TRUE WHERE OTPID = " + rs.getInt("OTPID");
            db.Update(updateOtpQuery);

            JOptionPane.showMessageDialog(this, "Xác minh thành công!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Mã OTP không hợp lệ hoặc đã hết hạn!");
        }

        db.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_btnxacnhanActionPerformed

    private void btnguilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguilaiActionPerformed
        try {
        String otp = String.format("%06d", new java.util.Random().nextInt(1000000));
        long expiryTime = System.currentTimeMillis() + 5 * 60 * 1000; // 5 phút

        DBAccess db = new DBAccess();
        String query = "UPDATE OTPs SET OTPCode = '" + otp + "', ExpiryTime = '"
                + new java.sql.Timestamp(expiryTime) + "', IsUsed = FALSE WHERE UserID = " + userId;
        int result = db.Update(query);

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Mã OTP mới đã được gửi tới email của bạn!");
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi gửi lại mã OTP.");
        }

        db.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_btnguilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguilai;
    private javax.swing.JButton btnxacnhan;
    private javax.swing.JTextField txtotp;
    // End of variables declaration//GEN-END:variables

}
